/* tslint:disable */
/* eslint-disable */
/**
 * Objects API
 * API for managing objects
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MarkerInstallPosition
 */
export interface MarkerInstallPosition {
    /**
     * 
     * @type {number}
     * @memberof MarkerInstallPosition
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof MarkerInstallPosition
     */
    y: number;
    /**
     * 
     * @type {number}
     * @memberof MarkerInstallPosition
     */
    z: number;
}
