/* tslint:disable */
/* eslint-disable */
/**
 * Objects API
 * API for managing objects
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ReadingsInner
 */
export interface ReadingsInner {
    /**
     * 
     * @type {number}
     * @memberof ReadingsInner
     */
    readingId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ReadingsInner
     */
    timestamp: Date;
    /**
     * 
     * @type {number}
     * @memberof ReadingsInner
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof ReadingsInner
     */
    porePressure?: number;
}
